version: '3'

services:

  mongodb:
    image: mongo:latest
    container_name: qr_mongo
    volumes:
      - './mongo/data:/data/db'
    env_file:
      - .env
    ports:
      - 27017:27017

  fastapi:
    build: 
      context: ./python
      dockerfile: Dockerfile
    image: QRdoc/pyhton
    container_name: qr_python
    environment:
      - project=${project}
      - MONGODB_URL=${MONGODB_URL}
    volumes: 
      - ./python:/data/qr-doc/
    depends_on:
      - mongodb
      - vue
    ports:
      - 8000:8000
    networks:
      - app-network
  
  vue:
    build:
      context: ./vue
      dockerfile: Dockerfile
    image: QRdoc/vue
    container_name: qr_vue
    ports:
      - '4173:4173'
    networks:
      - app-network
  
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: QRdoc/nginx
    container_name: qr_nginx
    ports:
      - 80:80
    networks:
      - app-network



networks:
  app-network:
    driver: bridge